Chat.och  = {
	INVALID_HTTP_TYPE : 0,
	COMMAND_NOT_FOUND : 1,
 	PUSH_ACTION_NOT_FOUND : 2,
 	DATA_ACTION_NOT_FOUND : 3,
 	NO_SESSION_ID : 6,
 	USER_NOT_EQUAL_TO_OC_USER : 7,
 	NO_TIMESTAMP : 8,
 	NO_CONV_ID : 9,
 	NO_USER_TO_INVITE : 10,
 	USER_EQUAL_TO_USER_TO_INVITE : 11,
 	USER_TO_INVITE_NOT_OC_USER : 12,
 	NO_CHAT_MSG : 13
};