<?php
include(__DIR__ . '/../lib/compat.php');
// Vendor client-side code
vendor_script('chat', array(
	'angular/angular.min',
	'angular-enhance-text/build/angular-enhance-text.min',
	'angular-resource/angular-resource.min',
	'angular-sanitize/angular-sanitize.min',
	'jquery-autosize/jquery.autosize.min',
	'moment/min/moment.min',
	'rangyinputs-jquery-src/index',
	'strophe/strophe.min',
	'emojione/lib/js/emojione.min'
));
vendor_style('chat', array(
	'emojione/assets/sprites/emojione.sprites',
	'emojione/assets/css/emojione.min',
));
if (defined('DEBUG') && DEBUG) {
	vendor_script('chat','angular-mocks/angular-mocks');
}

// Chat app client-side code
script('chat', 'main.min');
style('chat', 'main.min');
?>

<div
	ng-cloak
	ng-click="view.hide('invite', $event, ['invite-no-hide', 'invite-button']);view.hide('files', $event, ['files-no-hide', 'file-element', 'files-button']);view.hide('emojiContainer', $event, ['emoji-no-hide']);"
	ng-controller="ConvController"
	ng-app="chat"
	id="app"
>
	<!-- Variables which are needed to boot up the Chat app in JS-->
	<div style="display:none;" id="initvar">
		<?php echo $_['initvar'];?>
	</div>
	<div style="display:none" id="avatars-enabled">
		<?php var_export($_["avatars-enabled"]);?>
	</div>
	<div id="app-navigation" >
		<?php print_unescaped($this->inc('part.app-navigation')) ?>
	</div>
	<div id="app-content">
		<?php print_unescaped($this->inc('part.chat')) ?>
		<?php print_unescaped($this->inc('part.no-users')) ?>
		<?php print_unescaped($this->inc('part.no-backends')) ?>
	</div>
	<!-- popups -->
	<?php print_unescaped($this->inc('part.invite')) ?>
	<?php print_unescaped($this->inc('part.files')) ?>
	<?php print_unescaped($this->inc('part.xmpp')) ?>
	<!-- Translations are stored here, so they can be generated by PHP.
	This way they won't be fetched via JS -->
	<div id="translations">
		<span id="translations-attached">
			<?php p($l->t('{displayname} attached {path} to this conversation')); ?>
		</span>
        <span id="translations-removed">
			<?php p($l->t('{displayname} removed {path} from this conversation')); ?>
		</span>
	</div>
</div>